# Stage 1: Base build stage
FROM python:3.14-slim AS builder
 
# Create the app directory
RUN mkdir /app
 
# Set the working directory
WORKDIR /app
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
# Upgrade pip and install dependencies
RUN pip install --upgrade pip 
 
# Copy the requirements file first (better caching)
COPY requirements.txt /app/
 
# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
 
# Stage 2: Production stage
FROM python:3.14-slim
 
# Docker configuration
# RUN useradd -m -r appuser && \
#   mkdir /app && \
#   chown -R appuser /app

# OpenShift Security Fix: Grant the root group read/write/execute rights to app files
RUN chgrp -R 0 /app && chmod -R g=u /app
 
# Copy the Python dependencies from the builder stage
COPY --from=builder /usr/local/lib/libpython3.14.so.1.0 /usr/local/lib/libpython3.14.so.1.0
ENV LD_LIBRARY_PATH="/usr/local/lib"
COPY --from=builder /usr/local/lib/python3.14/site-packages/ /usr/local/lib/python3.14/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
 
# Set the working directory
WORKDIR /app
 
# Copy application code
COPY --chown=appuser:appuser . .
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
ENV DJANGO_SETTINGS_MODULE='globus_portal_framework.settings'
 
# Switch to non-root user
USER appuser
 
# Expose the application port
EXPOSE 8000 

# RUN python3 manage.py migrate
 
# Start the application using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "globus_portal_framework.wsgi:application"]
